### ISSUE TITLE
Calculate Impact of unavailable followers

### ISSUE THREAD

**Issue by Koriania** [AcidWeb/RENovate#2]
The "Calculate Impact of Unavailable Followers" is not check-able. There's no error message - it's just permanently grayed out.

It'd be really nice to know which of my inactive followers to activate. 

![wowscrnshot_061918_185659](https://user-images.githubusercontent.com/40410873/41630094-ddce7c68-73f2-11e8-81a6-587c7adc8dcf.jpg)

**Comment by AcidWeb** [comment]
I agree. Option is disabled because It is breaking mission UI and I not found fix yet.
