### ISSUE TITLE
Shadowlands errors & a wish

### ISSUE THREAD

**Issue by yoshimo** [AcidWeb/RENovate#4]
ID: 10
Error occured in: Global
Count: 1
Message: ..\AddOns\RENovate\RENovate.lua line 799:
   Usage: GetAvailableMissions([missionList,] garrFollowerTypeID)
Debug:
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "@RENovate\RENovate.lua"]:799: FillMissionCache()
   [string "@RENovate\RENovate.lua"]:148: OnEvent()
   [string "*:OnEvent"]:1:
      [string "*:OnEvent"]:1

It would be great if any SL version of this addon would be separate  one so we can still get the old content in an improved way.

**Comment by AcidWeb** [comment]
Most probably there will not be any SL version. I'm almost sure that this project will be discontinued. So I'm closing this issue.
